server:
  port: 80

spring:
  application:
    name: microservicecloud-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost1:7001/eureka,http://localhost2:7002/eureka,http://localhost3:7003/eureka
  instance:
    instance-id: microservicecloud-consumer-dept-80
    prefer-ip-address: true
