server:
  port: 7003

eureka:
  instance:
    hostname: localhost3
  client:
    register-with-eureka: false       # false 表示不向注册中心注册自己
    fetch-registry: false             # false 表示自己就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖该地址
      defaultZone: http://localhost1:7001/eureka/,http://localhost2:7002/eureka/